---
title: "SF Bikeshare Status - Modeling With H2O"
output: html_notebook
---


  
## Setup    
  Load the relevant libraries.
```{r}
# {r, message=FALSE, warning=FALSE}

# rm(list = ls())
# .rs.restartR()


library("tidyverse")
# install.packages("data.table")
library("data.table")
# library("lubridate")
# install.packages("timetk")
# library("timetk")
# library("DBI")
# install.packages("RSQLite")
# library("RSQLite")
# install.packages("h2o")
library("h2o")

```
  
    
  Session Info.
```{r}

sessionInfo()

```


  Setup the root directory.
```{r "setup", include = FALSE}

require("knitr")

opts_knit$set(root.dir = "/home/rstudio/Dropbox/_AWS/SF_Bikeshare_Status/")

```
  
    
  Setting `wd` as the working directory.
```{r}

wd <- getwd()

wd

```
  
    
  Get the base dataset.
```{r}

id_split <-
  read_rds(path = paste0(wd,
                         "/Data/Interim/",
                         "id_split.rds"
                         )
           )


pmap(.l = list(a = id_split,
               b = names(id_split)
               ),
     .f = function(a, b) {
       message(b)
       
       str(a)
       }
     )

View(id_split$`10` %>% head(1000))

```



```{r}

row_cnt <- id_split$`10` %>% 
  nrow()

split_pt_test <- round(0.80 * row_cnt, digits = 0) + 1
split_pt_train <- round(0.64 * row_cnt, digits = 0)
split_pt_valid <- round(split_pt_train * 0.80, digits = 0)

```




Save the data.
```{r}

write_rds(sss,
          path = paste0(wd,
                        "/Data/Interim/",
                        "sss.rds"
                        )
          )

```
  
    
  Remove no-longer-needed files.
```{r}

rm(status_trips_time)

```
  

