---
title: "SF Bikeshare Status - Modeling Setup"
output: html_notebook
---


  
## Setup    
  Load the relevant libraries.
```{r}
# {r, message=FALSE, warning=FALSE}

# rm(list = ls())
# .rs.restartR()


library("tidyverse")
# install.packages("data.table")
library("data.table")
# library("lubridate")
# install.packages("timetk")
# library("timetk")
# library("DBI")
# install.packages("RSQLite")
# library("RSQLite")

```
  
    
  Session Info.
```{r}

sessionInfo()

```


  Setup the root directory.
```{r "setup", include = FALSE}

require("knitr")

opts_knit$set(root.dir = "/home/rstudio/Dropbox/_AWS/SF_Bikeshare_Status/")

```
  
    
  Setting `wd` as the working directory.
```{r}

wd <- getwd()

wd

```
  
    
  Get the base dataset.
```{r}

status_trips_time <-
  read_rds(path = paste0(wd,
                         "/Data/Interim/",
                         "status_trips_time.rds"
                         )
           )

message("status_trips_time")
str(status_trips_time)
# View(status_trips_time %>% head(1000))

```
  
    
  Split the dataset by `station_id` and cleanup the resulting dataset.
```{r}

# initial split
id_split <-
  status_trips_time %>% 
  split(.$station_id)


# data cleanup
id_split <-
  pmap(.l = list(a = id_split),
       .f = function(a) {
         df = a %>% 
           tail(n = -3) %>% # remove first three rows because of lags
           mutate_if(is.factor, factor) %>% 
           select(-docks_avail_now) %>% # remove `docks_avail_now` because you won't know this at the time of prediction
           as.data.table() %>% 
           setkey(time_rnd, station_id)
         
         return(df)
         }
       )

```
  
    
  Create splits for train/valid/test.
```{r}

# create a function for the split
func_train_valid_test <-
  function(data, pct_train, pct_valid, ...) {
    row_cnt = data %>% nrow()
    
    pct_train = pct_train
    pct_valid = pct_valid
    pct_test = 1 - pct_train - pct_valid
    
    split_pt_train = round(pct_train * row_cnt, digits = 0)
    split_pt_valid = round((pct_train + pct_valid) * row_cnt, digits = 0)
    
    dt =
      data %>% 
      arrange(time_rnd) %>% 
      mutate(row_num = row_number(),
             data_type = case_when(row_num < split_pt_train ~ "01_train",
                                   between(x = row_num,
                                           lower = split_pt_train,
                                           upper = split_pt_valid,
                                           incbounds = TRUE
                                           ) ~ "02_valid",
                                   TRUE ~ "03_test"
                                   ) %>% 
               factor()
             )
    }


# run the function
id_split <-
  pmap(.l = list(a = id_split),
       .f = function(a) {
         data = func_train_valid_test(data = a, pct_train = 0.70, pct_valid = 0.15)
         }
       )


# confirmation
pmap(.l = list(a = id_split,
               b = names(id_split)
               ),
     .f = function(a, b) {
       message(b)
       
       str(a)
       }
     )

View(id_split$`10` %>% head(1000))

```
  
    
  Save the data.
```{r}

write_rds(id_split,
          path = paste0(wd,
                        "/Data/Interim/",
                        "id_split.rds"
                        )
          )

```
  
    
  Remove no-longer-needed files.
```{r}

rm(status_trips_time)

```
  

