---
title: "SF Bikeshare Status - Feature Engineering"
output: html_notebook
---


  
## Setup    
  Load the relevant libraries.
```{r}
# {r, message=FALSE, warning=FALSE}

# rm(list = ls())
# .rs.restartR()


library("tidyverse")
# install.packages("data.table")
library("data.table")
library("lubridate")
# install.packages("timetk")
library("timetk")
# library("DBI")
# install.packages("RSQLite")
# library("RSQLite")

```
  
    
  Session Info.
```{r}

sessionInfo()

```


  Setup the root directory.
```{r "setup", include = FALSE}

require("knitr")

opts_knit$set(root.dir = "/home/rstudio/Dropbox/_AWS/SF_Bikeshare_Status/")

```
  
    
  Setting `wd` as the working directory.
```{r}

wd <- getwd()

wd

```
  
    
  Get the base dataset.
```{r}

status_trips <-
  read_rds(path = paste0(wd,
                         "/Data/Interim/",
                         "status_trips.rds"
                         )
           )

message("status_trips")
str(status_trips)
# View(status_trips %>% head(1000))

```
  
    
  Create lagged variables.
```{r}

lags <-
  status_trips %>% 
  rename(bikes_avail_now = bikes_available,
         docks_avail_now = docks_available,
         Customer_cnt_05min_window_end = Customer_cnt_5min_window_end,
         Customer_cnt_05min_window_start = Customer_cnt_5min_window_start,
         Subscriber_cnt_05min_window_end = Subscriber_cnt_5min_window_end,
         Subscriber_cnt_05min_window_start = Subscriber_cnt_5min_window_start
         ) %>% 
  group_by(station_id) %>% 
  mutate(bikes_avail_lag05 = dplyr::lag(bikes_avail_now, n = 1),
         bikes_avail_lag10 = dplyr::lag(bikes_avail_now, n = 2),
         bikes_avail_lag15 = dplyr::lag(bikes_avail_now, n = 3),
         Customer_cnt_10min_window_end = dplyr::lag(Customer_cnt_05min_window_end, n = 1),
         Customer_cnt_15min_window_end = dplyr::lag(Customer_cnt_05min_window_end, n = 2),
         Customer_cnt_10min_window_start = dplyr::lag(Customer_cnt_05min_window_start, n = 1),
         Customer_cnt_15min_window_start = dplyr::lag(Customer_cnt_05min_window_start, n = 2),
         Subscriber_cnt_10min_window_end = dplyr::lag(Subscriber_cnt_05min_window_end, n = 1),
         Subscriber_cnt_15min_window_end = dplyr::lag(Subscriber_cnt_05min_window_end, n = 2),
         Subscriber_cnt_10min_window_start = dplyr::lag(Subscriber_cnt_05min_window_start,
                                                        n = 1),
         Subscriber_cnt_15min_window_start = dplyr::lag(Subscriber_cnt_05min_window_start,
                                                        n = 2)
         ) %>% 
  ungroup() %>%  
  as.data.table() %>% 
  setkey(station_id, time_rnd)

str(lags)
# View(lags %>% head(1000))

```
  
    
  Create time-based variables.
```{r}

# status_trips %>% mutate(date = as_date(time_rnd)) %>% select(date) %>% distinct() %>% nrow()
date_min <- min(lags$time_rnd)
date_max <- max(lags$time_rnd)

time_dt <-
  data.frame(date = seq.POSIXt(from = date_min, to = date_max, by = "5 mins")) %>% 
  tk_index() %>% 
  tk_get_timeseries_signature() %>% 
  select(-index.num,
         -diff,
         -year.iso,
         -month,
         -month.xts,
         -second,
         -hour12,
         -am.pm,
         -wday,
         -wday.xts,
         -qday,
         -yday,
         -week.iso,
         -week2,
         -week3,
         -week4,
         -mday7
         ) %>% 
  rename(date = index) %>% 
  mutate_at(vars(year:week), as.character) %>% 
  mutate_at(vars(year:week), as.factor) %>% 
  as.data.table() %>% 
  setkey(date)

str(time_dt)

```
  
    
  Merge the datasets.
```{r}

status_trips_time <-
  merge(x = lags,
        y = time_dt,
        by.x = "time_rnd",
        by.y = "date",
        all.x = TRUE
        ) %>% 
  setkey(station_id, time_rnd)

str(status_trips_time)
View(status_trips_time %>% head(1000))

```
  
    
  Save the data.
```{r}

write_rds(status_trips_time,
          path = paste0(wd,
                        "/Data/Interim/",
                        "status_trips_time.rds"
                        )
          )

```
  
    
  Remove no-longer-needed files.
```{r}

rm(status_trips, lags, time_dt, date_min, date_max)

```
  

